### PR TITLE
Add pagination functionality with detailed comments

### PR DESCRIPTION
**Pull request by Yashop181**
This pull request adds pagination to navigate movie results in the App component. Detailed comments were added to enhance code clarity and maintainability.

Key Changes:

Implemented pagination controls with PaginationControls component.
Updated API calls to fetch movies based on current page.
Enhanced code readability with detailed comments.

Screenshot:

Screenshot (1149)

Screenshot (1150)

### CODE REVIEW

**Review by maestro-00 — CHANGES_REQUESTED** [review]
Everything is in order.
I especially like the detailed commenting.
But before this is merged, could you modify your code to only show the pagination tab when the resultset requires pagination.

I have realized that even when no resultset is returned, the pagination tab is still shown which is not desired

**Comment by maestro-00** [comment]
Also, make sure the branch you are using to create the PR is up to date with the master branch of the repo.

**Comment by Yashop181** [comment]
Sure, I will ensure that the branch I am using to create the PR is up to date with the master branch of the repo.

**Comment by Yashop181** [comment]
Thank you for your feedback, @Lukada-taiya . I have made the requested changes to ensure the pagination tab only appears when the result set requires pagination. Additionally, I have updated my branch with the latest changes from the master branch.

**Comment by maestro-00** [comment]
Everything seems to be in order. Well done

**Pull request merged**
